In [1]:
import sys
import os
sys.path.append(os.path.abspath(os.path.join('..')))
import numpy as np

In [2]:
# forward pass
# Dummy Inputs
x = np.array([0.05, 0.10])
y = np.array([0.01,0.99])

weights1 = np.array([[0.15, 0.25],[0.20, 0.30]])
bias1 = np.array([0.35,0.35])

weights2 = np.array([[0.40, 0.5],[0.45, 0.55]])
bias2 = np.array([0.60,0.60])

In [3]:
import src.LinearLayer as ll
import src.Loss as Loss

layer1 = ll.Linear(2, 2, weights=weights1, bias=bias1)
layer2 = ll.Sigmoid()
layer3 = ll.Linear(2, 2, weights=weights2, bias=bias2)
layer4 = ll.Sigmoid()

loss = Loss.MSELoss()


In [4]:
# Linear function
h = np.matmul(x,weights1)+bias1

# non-linear activation(logistic)
h1 = 1/(1+np.exp(-h))

# final output layer
o = np.matmul(h1,weights2)+bias2

# non-linear activation(logistic)
o1 = 1/(1+np.exp(-o))

In [5]:
o1 == layer4(layer3(layer2(layer1(x))))

array([ True,  True])

In [6]:
E = 0.5*(np.sum((y-o1)**2))

E == loss(layer4(layer3(layer2(layer1(x)))), y)

np.True_

Backward propagation

In [7]:
o1-y == loss.backward()

array([ True,  True])

In [8]:
# o1 w.r.t o
(o1-y)*(o1*(1-o1)) == layer4.backward(loss.backward())

array([ True,  True])

In [25]:
dw2 = np.matmul(h1.reshape(-1,1), ((o1-y)*(o1*(1-o1))).reshape(1,-1))
db2 = (o1-y)*(o1*(1-o1))

In [26]:
dw2 == layer3.dw

array([[ True,  True],
       [ True,  True]])

In [27]:
db2 == layer3.db

array([ True,  True])

In [ ]:
np.matmul((o1-y)*(o1*(1-o1)), weights2.T) == layer3.backward(layer4.backward(loss.backward()))

array([[ True,  True]])

In [28]:
dE_dh1 = np.matmul((o1-y)*(o1*(1-o1)), weights2.T) 

In [31]:
dE_dh1*(h1*(1-h1)) == layer2.backward(layer3.backward(layer4.backward(loss.backward())))

array([[ True,  True]])

In [32]:
np.matmul(dE_dh1*(h1*(1-h1)), weights1.T) == layer1.backward(layer2.backward(layer3.backward(layer4.backward(loss.backward()))))

array([[ True,  True]])

In [39]:
dw1 = np.matmul(x.reshape(-1,1), (dE_dh1*(h1*(1-h1))).reshape(1,-1))
db1 = (dE_dh1*(h1*(1-h1))).reshape(1,-1)

In [41]:
dw1 == layer1.dw

array([[ True,  True],
       [ True,  True]])

In [42]:
db1 == layer1.db

array([[ True,  True]])